
[custom_entity]

	[custom_entity.sample]
		type_name = "modid:type_name"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "ZOMBIE"
		texture_location = "modid:texture_location"

[custom_weaponry]

	[custom_weaponry.hexblade_earth_hammer_1]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "AXE"
		registry_name = "hexblades:earth_hammer_1"

	[custom_weaponry.hexblade_ice_katana_2]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "KATANA"
		registry_name = "hexblades:ice_katana_2"

	[custom_weaponry.hexblade_ice_katana_1]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "KATANA"
		registry_name = "hexblades:ice_katana_1"

	[custom_weaponry.hexblade_thunder_dagger_1]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "DAGGER"
		registry_name = "hexblades:thunder_knives_right1"

	[custom_weaponry.hexblade_thunder_dagger_2]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "DAGGER"
		registry_name = "hexblades:thunder_knives_right2"

	[custom_weaponry.hexblade_blood_sword]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SWORD"
		registry_name = "hexblades:blood_sword"

	[custom_weaponry.hexblade_water_saber_2]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SWORD"
		registry_name = "hexblades:water_saber_2"

	[custom_weaponry.hexblade_water_saber_1]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SWORD"
		registry_name = "hexblades:water_saber_1"

	[custom_weaponry.hexblade_bolt_dagger_2]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "DAGGER"
		registry_name = "hexblades:thunder_knives_left2"

	[custom_weaponry.eidolon_sapping_sword]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SWORD"
		registry_name = "eidolon:sapping_sword"

	[custom_weaponry.hexblade_bolt_dagger_1]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "DAGGER"
		registry_name = "hexblades:thunder_knives_left1"

	[custom_weaponry.hexblade_flame_sword_2]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SWORD"
		registry_name = "hexblades:flame_sword_2"

	[custom_weaponry.hexblade_flame_sword_1]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SWORD"
		registry_name = "hexblades:flame_sword_1"

	[custom_weaponry.hexblade_earth_hammer_2]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "AXE"
		registry_name = "hexblades:earth_hammer_2"

[custom_armor]

	[custom_armor.sample]
		stun_armor = 0.0
		weight = 0.0
		registry_name = "modid:registryname"

